### ISSUE TITLE
[PENDING] Filename with Unicode characters

### ISSUE THREAD

**Issue by sergeevabc** [charonn0/VT-Hash#11]
Dear Mr. Lambert,
VT Hash Checker 1.59 seems to be unable to handle a file with Russian name. Could you fix it, please?

![](https://a.safe.moe/L3tzu.png)

**Comment by charonn0** [comment]
Hi, sergeevabc. Can you tell me whether this problem happens every time you try to upload such a file, just for this specific file, or has only happened once?

**Comment by sergeevabc** [comment]
Mr. Lambert, it seems to happen with any file which name contains Unicode characters.
For example, let’s create ```bitte schön.txt``` with some random data, then use VTHC against it.

![](https://files.catbox.moe/7cvve7.png)

**Comment by charonn0** [comment]
I can't replicate this error on my computer; Cyrillic and Unicode paths work just fine. 

Are you using an English language version of Windows? I think it may have something to do with the fact that I'm using the Windows short path instead of the full path, and that might be affecting the short path.

**Comment by sergeevabc** [comment]
> Are you using an English language version of Windows?

Yes.

>  I think it may have something to do with…

At least some weird name conversion happens because valid ones are garbled in the errror dialogue.
For examples, ```ö``` (o with umlaut) turns into ```C6```, let alone ```Ж. Эллюль Технологический блеф.doc```.

**Comment by charonn0** [comment]
I'm still having trouble reproducing this but I'll keep working on it.

**Comment by sergeevabc** [comment]
Hmm, tried another solutions: [official][1] and [non-official][2], both upload without errors.

[1]: https://www.virustotal.com/en/documentation/desktop-applications/
[2]: https://github.com/Genbox/VirusTotalContextMenu

**Comment by sergeevabc** [comment]
Oh, the issue is still here. :(

**Comment by charonn0** [comment]
Yes, unfortunately I haven't been able to reproduce the problem. Cyrillic characters work just fine no matter how I test it. And I can't fix a problem that I can't see.

**Comment by sergeevabc** [comment]
It seems we could use help from someone familiar with Windows issues related to codepages or something like that. Alas, there is no button to reach out to the public for help. Right, perhaps our environments are different and that’s why you’re currently unable to reproduce the issue, but what about the error message depicted above? Doesn’t it narrow down the scope of where to look?

**Comment by charonn0** [comment]
Yes, the error message is coming from libcurl. It's telling us that it can't read the file, and since the file path it gives is corrupted we know why. But you're using the same version (7 x64) and language (English) that I'm testing on, so I'm at a loss as to why it doesn't work on your machine.

**Comment by sergeevabc** [comment]
Unicode, Libcurl, [let’s see][1]… We’re definitely not alone.

[1]: https://encrypted.google.com/search?q=libcurl+error+26+unicode

**Comment by sergeevabc** [comment]
Since Curl fails to read specific filename, perhaps there is something wrong with “GetFileName function”.

**Comment by charonn0** [comment]
What GetFileName function are you referring to?

**Comment by sergeevabc** [comment]
There is no specific GetFileName function, Mr. Lamber. Being a mere user, I am just thinking out loud.

**Comment by charonn0** [comment]
I see what you mean, but it's difficult to debug a problem that I can't reproduce and study. 

> something might be wrong with _how we tell_ which filename to read

Clearly that's the case, and I think the solution is to _not_ tell libcurl to use a path at all. I just made a [change](https://github.com/charonn0/VT-Hash/commit/155c65341523c1e42a4bfadc4aced9dc725f8ff0) so that VT Hash Check handles the file reading itself; since VT Hash Check uses UTF-8 exclusively that should solve any and all problems with matching encodings across the ABI. I should be releasing a new version with this change in the next day or so.

**Comment by sergeevabc** [comment]
> I should be releasing a new version with this change in the next day or so.

Ready to test it in the raw right now, if that suits you.

**Comment by charonn0** [comment]
Just released now. I was having problem with github's upload feature but I got it to work in less than day :)

You can download the latest release from the [releases](https://github.com/charonn0/VT-Hash/releases) page or by using the update feature in VT Hash Check. Let me know if it fixes the problem for you.

**Comment by sergeevabc** [comment]
Hooray! File ```спасибо.txt``` has been [uploaded][1] for analysis successfully, so the issue is fixed.
Let’s take a break & enjoy the fruits of joint work in the face of upcoming issues (I’ll create a few soon).

[1]: https://www.virustotal.com/en/file/33d554b783018a1f3724d43af6d2d5e1f1f2578355b3da564bd36e1a8087e17e/analysis/
