### ISSUE TITLE
This project is alive?

### ISSUE THREAD

**Issue by Mike-Reddick** [charonn0/VT-Hash#14]

**Comment by charonn0** [comment]
It's not quite dead, though I don't plan on making any updates to the current code except for bug fixes.

**Comment by Nightblade** [comment]
@charonn0  Is there an alternative you can recommend?

**Comment by charonn0** [comment]
I still use this on my own systems. If you're looking for alternatives then check the Virus Total website, which has a list of some tools: https://docs.virustotal.com/docs/desktop-apps

**Comment by Nightblade** [comment]
I'm still using it too, thanks! 👍 

I had a quick look at the apps in that link but I couldn't find anything as convenient as your app.
