### ISSUE TITLE
[Bug] Unable to Connect to VT

### ISSUE THREAD

**Issue by Jack1789** [charonn0/VT-Hash#15]
Hi, since a few days ago, I'm getting this while trying to use your program:

![vth](https://user-images.githubusercontent.com/54497604/94624971-08babf00-028e-11eb-81c0-c16c2320be00.png)

**Comment by charonn0** [comment]
The `403 Forbidden` error usually means your API key is invalid. Since it began happening only recently I'd suggest verifying that your VirusTotal account hasn't been suspended.

**Comment by Jack1789** [comment]
You are right, I changed it for a new one and now it works fine again.

Thanks.
