### ISSUE TITLE
Connection error on rescan request

### ISSUE THREAD

**Issue by pigpen2** [charonn0/VT-Hash#16]
Since about six months, every time i request a rescan, regardless of the delay, i always get the window with 403 Forbidden error.
I tried three different public keys on two different windows installation, with all the available options, but it always return the same error.
Thank you

**Comment by charonn0** [comment]
It looks like rescan requests are now limited to premium API keys. https://developers.virustotal.com/reference#file-rescan

I just released an update that handles this error better.

**Comment by pigpen2** [comment]
Thanks for your quick response and for the update.
I tested the new release, now it's all clear.
