### ISSUE TITLE
VTHash detected as "BScope.Trojan.Packed" in VirusTotal

### ISSUE THREAD

**Issue by ezxpro** [charonn0/VT-Hash#17]
From the 1.6.2 version download here on GitHub, the VBA engine detects it as a trojan.

https://www.virustotal.com/gui/file/23e6f809f416af390942b4827787452051d973225ed19304d22c562af1ff0916/detection

The uninstaller (unins000.exe) is detected by 3 engines.

https://www.virustotal.com/gui/file/944f720556fe5007a7bc113e0e0d7dd3c92835985a55c8d577400b52caf7bd98/detection

The rest of the files in the install folder are undetected

**Comment by charonn0** [comment]
Thanks for the heads up. This is a false positive and there's not a whole lot to be done about it except report it to the AV company.

**Comment by ezxpro** [comment]
@charonn0 okay, I talked to MalwareBytes support today, they confirmed it's a false positive.

For anyone out there who might be concerned, check this out: https://forums.malwarebytes.com/topic/269947-trojan-detected-in-vt-file-hash/?tab=comments#comment-1435751
