### ISSUE TITLE
VT can now manage 650Mo files 

### ISSUE THREAD

**Issue by tox1982** [charonn0/VT-Hash#19]
Can you update your code to manage 650Mo files ? Because now VirusTotal accept 650Mo per file and VT-Hash is limited to 128Mo.
Thanks a lot (I can't found a key for real studio to build it myself and don't want to buy it just for a small change).

**Comment by charonn0** [comment]
I made the size check optional and updated the limits. Please download [release 1.63](https://github.com/charonn0/VT-Hash/releases/download/v1.63/VT.Hash.zip) or run the self-update feature.
