### ISSUE TITLE
Is Google essentially preventing users of this tool from performing new scans?

### ISSUE THREAD

**Issue by Gitoffthelawn** [charonn0/VT-Hash#20]
This tool looks very useful.  Thank you for writing and publishing it as open-source.

If I'm understanding #16 correctly, Google no longer allows public API keys to perform new malware scan.  Is this bad news correct?

If so, it seems, with sadness, like it severely reduces the benefits of your program.  Malware is constantly evolving, and a scan done days ago (or longer) isn't nearly as meaningful as a recent scan.

It also looks like Google is charging more money than most people make in a year for a premium API key that lets people perform new scans.

If all the above is correct, it seems like your program has, regrettably, lost much of it's value due to Google's severe restrictions and exorbitant prices.

My question: Is the above basically correct?

Thank you again, and if the above is correct, well, that's really a shame.

**Comment by charonn0** [comment]
It's actually **re**-scan requests that are behind a paywall now. Uploads of new files to be scanned are still accepted with free keys (with size limits).

**Comment by Gitoffthelawn** [comment]
> It's actually **re**-scan requests that are behind a paywall now. Uploads of new files to be scanned are still accepted with free keys (with size limits).

Thanks.  Unfortunately, VT doesn't seem to perform updated (current) scans on its own, so I find re-scans to be necessary for most files.  Otherwise, the scan results reflect malware definitions and heuristics that are days/weeks/months/years old.  I have a hunch many people don't realize such results are often worse than meaningless as they give a false sense that a file has no detections or contains malware due to false positives that have been rectified.

About 90% of the files I upload to VT have already been scanned in the past, but the scans were performed with definitions and heuristics that are outdated.

**Comment by charonn0** [comment]
Ah, I misread your question as being about uploads. You can still request a rescan from the full results page on the virustotal.com website.

**Comment by Gitoffthelawn** [comment]
> Ah, I misread your question as being about uploads. You can still request a rescan from the full results page on the virustotal.com website.

No problem.  Just to be sure I'm not missing something obvious (or not so obvious), to perform the re-scan from the full results page, one has to do that within a web browser (and not within the shell extension), right?

**Comment by charonn0** [comment]
Correct. The feature is still offered by the results window, but the API request will fail if your API key isn't authorized. In which case you have to open the results in your browser to access rescanning.

**Comment by Gitoffthelawn** [comment]
> Correct. The feature is still offered by the results window, but the API request will fail if your API key isn't authorized. In which case you have to open the results in your browser to access rescanning.

Thanks again.  And, of course, Google has made that API key so expensive that only large businesses or the uber rich can afford to buy one.  `<sarcasm>`Gotta love Google.`</sarcasm>`

Ironically, if more people performed re-scans on VirusTotal, it would actually help Google and digital security overall.
