### ISSUE TITLE
Solved: Untrusted SSL certificate with Netskope 

### ISSUE THREAD

**Issue by WDGroll** [charonn0/VT-Hash#21]
If Netskope is active, an untrusted SSL certificate is reported and the check is aborted. The solution is the same as that which also solves the problems with Netskope and MSYS2:

https://stackoverflow.com/questions/69348953/certificate-error-when-trying-to-install-msys2-packages-on-windows-server

The certificates extracted in this way must then be converted into PEM format and added to the default certificates "VTHash Resources\DEFAULT_CA_INFO_PEM" in the installation directory. Adding to the "certlist.pem" in the user path didn't work for me.

https://stackoverflow.com/questions/991758/how-to-get-pem-file-from-key-and-crt-files

**Comment by charonn0** [comment]
You can also add `--insecure` to the command line in the registry to disable SSL certificate validation.

```
Windows Registry Editor Version 5.00

[HKEY_CLASSES_ROOT\*\shell\vthash\command]
@="\"C:\\Program Files (x86)\\Boredom Software\\VT Hash Check\\VTHash.exe\" --insecure \"%1\""
```
