### ISSUE TITLE
Option to disable file upload dialog

### ISSUE THREAD

**Issue by Noir-** [charonn0/VT-Hash#4]
Could you add an option to suppress the dialog to upload the hashed file if it isn't in the database of Virustotal? I want to install it for some computer novices but I want to avoid the upload of eventually confidential data. I would love to create a pull request but the project is missing a `media` folder and there's a error with finding the `DEFAULT_CA_INFO_PEM` while building.

**Comment by charonn0** [comment]
That shouldn't be too difficult to add.

I guess I forgot to include the `DEFAULT_CA_INFO_PEM` in the repo. It's part of the RB-libcURL library and can be found [here](https://github.com/charonn0/RB-libcURL/blob/master/DEFAULT_CA_INFO_PEM).

**Comment by Noir-** [comment]
Thank you, this resolves this issue.
However, now I get two more issues:
![vt_hash_check_build_err](https://cloud.githubusercontent.com/assets/6486186/16374863/bfced218-3c58-11e6-9018-a61471599790.png)

Further I realized that could I run the code but not build it without spending money for the IDE. This leads me to the question if it still makes sense that I implement this feature. Since I'm not a Xojo developer it wouldn't make much sense for me to buy it for a simple code change.

**Comment by charonn0** [comment]
It looks like you're using the the Xojo IDE, which has made a number of breaking changes to the standard library. VTHC is built using Realstudio 2011r4.3. These errors appear to be caused by ambiguity between the old `String` datatype and the new`Text` datatype.

**Comment by charonn0** [comment]
> the project is missing a media folder and there's a error with finding the DEFAULT_CA_INFO_PEM

[Fixed](https://github.com/charonn0/VT-Hash/commit/a029c6a349d98745b79b70b82e57e330612c5fa3) the missing DEFAULT_CA_INFO_PEM reference. The images folder is there, but you probably need to tell the IDE where to find the corresponding directory on your computer ([/GUI/Images](https://github.com/charonn0/VT-Hash/tree/master/GUI/Images) relative to the project file). 

Also just [added](https://github.com/charonn0/VT-Hash/commit/3b04b9e649015e408b2493b6f783f63b1890c10a) a new preference to permit uploading. If not permitted then the user is merely informed that the file was not found. 
![vtnoupload](https://cloud.githubusercontent.com/assets/585485/16401772/f485070a-3c9b-11e6-95d1-c45d94b1396d.png)

By default uploads are allowed (old behavior.) Untick the checkbox in the settings window to disable uploads. Users can re-enable uploads through the same checkbox. [This](https://github.com/charonn0/VT-Hash/files/336160/VTHash_test.zip) is an exe built from the latest revision which includes these changes. Drop it in the VT Hash install folder and give it a whirl.

**Comment by Noir-** [comment]
Awesome! It seems working by just dropping in the new build. I think this can be closed.
